### ISSUE TITLE
Fail to install in JupyterLab 1.0.0

### ISSUE THREAD

**Issue by dclong** [tslaton/jupyterlab-favorites#1]
Got the following error message when running `sudo jupyter labextension install jupyterlab-favorites`.

```
An error occured.
ValueError: "jupyterlab-favorites" is not a valid npm package
See the log file for details:  /tmp/jupyterlab-debug-4qet0c3g.log
```

**Comment by tslaton** [comment]
Yeah, I haven't released it yet. Thanks for your interest!

I'm still working on it. Should release within approximately a week.

**Comment by dclong** [comment]
Looking forward to it!

**Comment by dclong** [comment]
Saw the release. It's super cool!
